# Generated by Django 5.1.6 on 2025-04-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_create_time_alter_user_update_time"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username", "password", "email"],
                name="accounts_us_usernam_982a75_idx",
            ),
        ),
    ]
