# Generated by Django 5.1.6 on 2025-04-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_accounts_us_usernam_982a75_idx"),
        (
            "categories",
            "0002_remove_category_parent_id_alter_category_create_time_and_more",
        ),
        ("text_app", "0002_alter_article_create_time_alter_article_update_time"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["id", "author_id"], name="text_app_ar_id_5ac794_idx"
            ),
        ),
    ]
