# Generated by Django 5.1.6 on 2025-04-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent_id",
        ),
        migrations.AlterField(
            model_name="category",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="update_time",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
